In [8]:
import csv
with open('data/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [15]:
sum(float(d['cty']) for d in mpg) / len(mpg)

3945.0

In [18]:
len(mpg)

234

In [21]:
for d in mpg:
    d = float(d)
    print(sum((d['cty'])))

TypeError: float() argument must be a string or a number, not 'collections.OrderedDict'

In [25]:
def addition(n): 
    return n + n 

numbers = (1, 2, 3, 4) 

result = map(addition, numbers) 

print(list(result)) 

[2, 4, 6, 8]


In [27]:
import numpy as np
m = np.array([[1,2,3,4],[4,5,6,7]])
m

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [29]:
m.shape

(2, 4)

In [31]:
n = np.arange(0,30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [35]:
n.reshape(5,3)


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [42]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [38]:
o.shape

(9,)

In [49]:
o.reshape(3,3)


array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [50]:
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [52]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [55]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])